import torch

# input_shape = (1, 3, 224, 224) for example
dummy_input = torch.randn(1, 3, 224, 224, device='cuda')

# load model
# torch default alexnet, the "alexnet.pt" is generated by defualt one.
# model = torchvision.models.alexnet(pretrained=True).cuda()
model = torch.load("alexnet.pt")

# inference mode
model.eval()

input_names = ["actual_input_1"] + ["learned_%d" % i for i in range(16)]
output_names = ["output1"]

torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)